### ISSUE TITLE
Katacoda Support: JSON Parse Issues

### ISSUE THREAD

**Issue by BenHall** [ArtKelly/katacoda-scenarios#1]
Hello,

Thank you for spending time creating content on Katacoda! I've noticed you've been encountering some JSON parsing issues which may be the reason the scenario doesn't always load. 

We're working on making the feedback better so please bear with us in the meantime.

If you need anything, please feel free to tag me on github issues or email us directly.

Looking forward to seeing your content! 

Thanks

Ben

**Comment by ArtKelly** [comment]
Hello Ben, 
Thank you for showing your support for my katacoda project. As far as I can tell i have resolved the issue myself as there was a syntax error in my index.json file. The problem being i did not leave a (,) after each step. After adding this (,) the scenario fully loaded and is working as expected.
Thanks
Art

**Comment by ArtKelly** [comment]
@BenHall Hi, 
Is it possible for me to run --class-path (+ some jar files) to initialise jshell in the env-init.sh file. I have already tried just to run the command on the lines after downloading the jar's which didn't work. Can you give me any guidance as for how to make this possible
Thanks, Art

**Comment by BenHall** [comment]
courseData is used for running commands in the background. If you use code instead the commands will be executed in the user terminal and as such, should provide you with the pre-initialised jShell

**Comment by ArtKelly** [comment]
Thank you Ben,
Everything is in working order now.
Art
